-- GENERATED by scripts/gen-scoring-parity.mts from tests/scoring-cases.ts.
-- Do not edit by hand: run `pnpm gen:scoring-parity` after changing the cases.
-- Holds public.score_market_pick to the exact numbers lib/scoring.ts is tested with.
begin;
\ir lib/helpers.sql

do $$
declare
  s uuid := pg_temp.make_season(2099);
  r record;
begin
  -- Same rule table as tests/scoring-cases.ts DEFAULT_RULES.
  delete from public.scoring_rules where season_id = s;
  insert into public.scoring_rules (season_id, market_type, rule_key, points) values
    (s, 'podium', 'exact_position', 10),
    (s, 'podium', 'in_podium', 4),
    (s, 'podium', 'all_exact_bonus', 25),
    (s, 'pole', 'exact', 8),
    (s, 'fastest_lap', 'exact', 6),
    (s, 'first_retirement', 'exact', 6),
    (s, 'safety_car', 'exact', 3),
    (s, 'sprint_winner', 'exact', 6);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 55 and r.hit_type = 'podium_exact_all',
    'podium all exact: expected 55/podium_exact_all, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd4')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 20 and r.hit_type = 'podium_partial',
    'podium two exact, one wrong: expected 20/podium_partial, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd4')), s, 1);
  perform pg_temp.check(r.points = 20 and r.hit_type = 'podium_partial',
    'podium two exact, one in podium: expected 20/podium_partial, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd3'), 'p3', pg_temp.driver(s, 'd2')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 18 and r.hit_type = 'podium_partial',
    'podium one exact, two swapped: expected 18/podium_partial, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd3'), 'p2', pg_temp.driver(s, 'd1'), 'p3', pg_temp.driver(s, 'd2')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 12 and r.hit_type = 'podium_partial',
    'podium three in wrong order: expected 12/podium_partial, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd4'), 'p2', pg_temp.driver(s, 'd5'), 'p3', pg_temp.driver(s, 'd1')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 4 and r.hit_type = 'podium_partial',
    'podium one in podium only: expected 4/podium_partial, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd4'), 'p2', pg_temp.driver(s, 'd5'), 'p3', pg_temp.driver(s, 'd6')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'podium none: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('pole', jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), s, 1);
  perform pg_temp.check(r.points = 8 and r.hit_type = 'exact',
    'pole exact: expected 8/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('pole', jsonb_build_object('driver_id', pg_temp.driver(s, 'd2')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), s, 1);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'pole miss: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('fastest_lap', jsonb_build_object('driver_id', pg_temp.driver(s, 'd3')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd3')), s, 1);
  perform pg_temp.check(r.points = 6 and r.hit_type = 'exact',
    'fastest lap exact: expected 6/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('sprint_winner', jsonb_build_object('driver_id', pg_temp.driver(s, 'd2')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd2')), s, 1);
  perform pg_temp.check(r.points = 6 and r.hit_type = 'exact',
    'sprint winner exact: expected 6/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('sprint_winner', jsonb_build_object('driver_id', pg_temp.driver(s, 'd2')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd5')), s, 1);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'sprint winner miss: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('first_retirement', jsonb_build_object('driver_id', pg_temp.driver(s, 'd6')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd6')), s, 1);
  perform pg_temp.check(r.points = 6 and r.hit_type = 'exact',
    'first retirement driver exact: expected 6/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('first_retirement', jsonb_build_object('driver_id', null), jsonb_build_object('driver_id', null), s, 1);
  perform pg_temp.check(r.points = 6 and r.hit_type = 'exact',
    'first retirement none/none: expected 6/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('first_retirement', jsonb_build_object('driver_id', null), jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), s, 1);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'first retirement none vs driver: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('first_retirement', jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), jsonb_build_object('driver_id', null), s, 1);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'first retirement driver vs none: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('safety_car', jsonb_build_object('value', true), jsonb_build_object('value', true), s, 1);
  perform pg_temp.check(r.points = 3 and r.hit_type = 'exact',
    'safety car yes/yes: expected 3/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('safety_car', jsonb_build_object('value', false), jsonb_build_object('value', false), s, 1);
  perform pg_temp.check(r.points = 3 and r.hit_type = 'exact',
    'safety car no/no: expected 3/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('safety_car', jsonb_build_object('value', false), jsonb_build_object('value', true), s, 1);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'safety car mismatch: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('pole', jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), s, 1.25);
  perform pg_temp.check(r.points = 10 and r.hit_type = 'exact',
    'pole x1.25 = 10: expected 10/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1.5);
  perform pg_temp.check(r.points = 83 and r.hit_type = 'podium_exact_all',
    'podium all exact x1.5 = 82.5 -> 83: expected 83/podium_exact_all, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('safety_car', jsonb_build_object('value', true), jsonb_build_object('value', true), s, 1.5);
  perform pg_temp.check(r.points = 5 and r.hit_type = 'exact',
    'safety car x1.5 = 4.5 -> 5: expected 5/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd3'), 'p3', pg_temp.driver(s, 'd2')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 1.25);
  perform pg_temp.check(r.points = 23 and r.hit_type = 'podium_partial',
    'podium 18 x1.25 = 22.5 -> 23: expected 23/podium_partial, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('pole', jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd1')), s, 2);
  perform pg_temp.check(r.points = 16 and r.hit_type = 'exact',
    'pole x2 = 16: expected 16/exact, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('podium', jsonb_build_object('p1', pg_temp.driver(s, 'd4'), 'p2', pg_temp.driver(s, 'd5'), 'p3', pg_temp.driver(s, 'd6')), jsonb_build_object('p1', pg_temp.driver(s, 'd1'), 'p2', pg_temp.driver(s, 'd2'), 'p3', pg_temp.driver(s, 'd3')), s, 2);
  perform pg_temp.check(r.points = 0 and r.hit_type = 'miss',
    'miss stays 0 under x2: expected 0/miss, got ' || r.points || '/' || r.hit_type);

  select * into r from public.score_market_pick('fastest_lap', jsonb_build_object('driver_id', pg_temp.driver(s, 'd3')), jsonb_build_object('driver_id', pg_temp.driver(s, 'd3')), s, 1.25);
  perform pg_temp.check(r.points = 8 and r.hit_type = 'exact',
    'fastest lap x1.25 = 7.5 -> 8: expected 8/exact, got ' || r.points || '/' || r.hit_type);
end $$;

rollback;
\echo 'OK: scoring_parity.sql (26 cases)'
