// Pure renderer shared by the generator script and the staleness test.
import { DEFAULT_RULES, SCORING_CASES, type ScoringCase } from "./scoring-cases.ts";

function sqlValue(v: string | boolean | null): string {
  if (v === null) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  return `pg_temp.driver(s, '${v}')`;
}

function jsonb(obj: Record<string, string | boolean | null>): string {
  const parts = Object.entries(obj).map(([k, v]) => `'${k}', ${sqlValue(v)}`);
  return `jsonb_build_object(${parts.join(", ")})`;
}

function caseBlock(c: ScoringCase): string {
  const label = c.name.replace(/'/g, "''");
  return [
    `  select * into r from public.score_market_pick('${c.type}', ${jsonb(c.pick)}, ${jsonb(c.result)}, s, ${c.multiplier});`,
    `  perform pg_temp.check(r.points = ${c.points} and r.hit_type = '${c.hitType}',`,
    `    '${label}: expected ${c.points}/${c.hitType}, got ' || r.points || '/' || r.hit_type);`,
  ].join("\n");
}

export function renderScoringParitySql(): string {
  const rules = Object.entries(DEFAULT_RULES).flatMap(([type, keys]) =>
    Object.entries(keys ?? {}).map(([key, points]) => `    (s, '${type}', '${key}', ${points})`),
  );
  return `-- GENERATED by scripts/gen-scoring-parity.mts from tests/scoring-cases.ts.
-- Do not edit by hand: run \`pnpm gen:scoring-parity\` after changing the cases.
-- Holds public.score_market_pick to the exact numbers lib/scoring.ts is tested with.
begin;
\\ir lib/helpers.sql

do $$
declare
  s uuid := pg_temp.make_season(2099);
  r record;
begin
  -- Same rule table as tests/scoring-cases.ts DEFAULT_RULES.
  delete from public.scoring_rules where season_id = s;
  insert into public.scoring_rules (season_id, market_type, rule_key, points) values
${rules.join(",\n")};

${SCORING_CASES.map(caseBlock).join("\n\n")}
end $$;

rollback;
\\echo 'OK: scoring_parity.sql (${SCORING_CASES.length} cases)'
`;
}
